version: '2'

services:
  rancher:
    image: rancher/server:stable
    restart: always
    ports:
    - "80:8080/tcp"
    volumes:
    - "rancher-data:/var/lib"
    privileged: true

volumes:
  rancher-data:
